### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by ua0lnj** [vdr-projects/vdr-plugin-image#1]
Hi.
I uploaded patches for image-plugin, look at it.
https://www.vdr-portal.de/forum/index.php?thread/132196-image-plugin-patch/&postID=1351751#post1351751
https://www.vdr-portal.de/forum/index.php?thread/132196-image-plugin-patch/&postID=1351753#post1351753

**Comment by M-Reimer** [comment]
Thanks. I already had them on my list for porting over.

Are you interested in having commit access here?
And then maybe add them by yourself?

**Comment by ua0lnj** [comment]
In general, I don’t want to support this plugin, I don’t use it, since in fact the MPV plugin can do it, but I check the image plugin with a softhddevice and therefore I needed it to work :)

**Comment by M-Reimer** [comment]
That's why the "vdr-projects" organization exists. You don't have to officially "adopt" the plugin (meaning you don't have it in your own "user context") and I could keep it as "Community maintained" on https://vdr-projects.github.io/. This leaves space for someone stepping in to "officially support" it. The only difference would be that you can use GIT features directly, don't have to export patches, probably don't have to post any update posts to VDR-Portal and... would reduce my work as I would not have to spend any time to manually import patches. :smile:

**Comment by ua0lnj** [comment]
Ok

**Comment by ua0lnj** [comment]
Done.
